export const deadlineEngineQaCorpus = [
  // ---------------------------------------------------------------------------
  // Deterministic rule engine
  // ---------------------------------------------------------------------------
  {
    id: 'calendar-after',
    layer: 'rules',
    description: '5 calendar days after an explicit date',
    input: {
      triggerDate: '2026-08-10',
      duration: 5,
      direction: 'after',
      unit: 'calendar-days',
      startDayConvention: 'exclude-trigger',
      holidayCalendar: 'none',
      endDayAdjustment: 'none',
    },
    expect: {
      answerDate: '2026-08-15',
      ruleVersion: 'deadline-rule-v1',
      workingScheduleId: 'standard_mon_fri',
    },
  },
  {
    id: 'calendar-before',
    layer: 'rules',
    description: '5 calendar days before an explicit date',
    input: {
      triggerDate: '2026-08-10',
      duration: 5,
      direction: 'before',
      unit: 'calendar-days',
      startDayConvention: 'exclude-trigger',
      holidayCalendar: 'none',
      endDayAdjustment: 'none',
    },
    expect: {
      answerDate: '2026-08-05',
    },
  },
  {
    id: 'business-exclude-trigger',
    layer: 'rules',
    description: '5 business days after Monday with trigger excluded',
    input: {
      triggerDate: '2026-08-10',
      duration: 5,
      direction: 'after',
      unit: 'business-days',
      startDayConvention: 'exclude-trigger',
      holidayCalendar: 'none',
      endDayAdjustment: 'none',
    },
    expect: {
      answerDate: '2026-08-17',
      skippedReasons: ['weekend'],
    },
  },
  {
    id: 'business-include-trigger',
    layer: 'rules',
    description: '5 business days with qualifying Monday counted as day 1',
    input: {
      triggerDate: '2026-08-10',
      duration: 5,
      direction: 'after',
      unit: 'business-days',
      startDayConvention: 'include-if-qualifying',
      holidayCalendar: 'none',
      endDayAdjustment: 'none',
    },
    expect: {
      answerDate: '2026-08-14',
    },
  },
  {
    id: 'include-nonqualifying-trigger',
    layer: 'rules',
    description: 'Including a Saturday does not count Saturday as a business day',
    input: {
      triggerDate: '2026-08-15',
      duration: 1,
      direction: 'after',
      unit: 'business-days',
      startDayConvention: 'include-if-qualifying',
      holidayCalendar: 'none',
      endDayAdjustment: 'none',
    },
    expect: {
      answerDate: '2026-08-17',
      skippedDates: ['2026-08-15', '2026-08-16'],
      skippedReasons: ['weekend'],
    },
  },
  {
    id: 'us-observed-holiday',
    layer: 'rules',
    description: 'US observed Independence Day is skipped',
    input: {
      triggerDate: '2026-07-02',
      duration: 1,
      direction: 'after',
      unit: 'business-days',
      startDayConvention: 'exclude-trigger',
      holidayCalendar: 'us',
      endDayAdjustment: 'none',
    },
    expect: {
      answerDate: '2026-07-06',
      skippedDates: ['2026-07-03', '2026-07-04', '2026-07-05'],
      skippedReasons: ['holiday', 'weekend'],
      skippedHolidayNameIncludes: 'Independence Day',
      holidayCalendar: 'us',
    },
  },
  {
    id: 'no-holiday-calendar-counts-weekday-holiday',
    layer: 'rules',
    description: 'Without a holiday calendar, weekday public holidays still count',
    input: {
      triggerDate: '2026-07-02',
      duration: 1,
      direction: 'after',
      unit: 'business-days',
      startDayConvention: 'exclude-trigger',
      holidayCalendar: 'none',
      endDayAdjustment: 'none',
    },
    expect: {
      answerDate: '2026-07-03',
    },
  },
  {
    id: 'final-next-business-day',
    layer: 'rules',
    description: 'Calendar-day candidate on Saturday moves forward to Monday',
    input: {
      triggerDate: '2026-08-14',
      duration: 1,
      direction: 'after',
      unit: 'calendar-days',
      startDayConvention: 'exclude-trigger',
      holidayCalendar: 'none',
      endDayAdjustment: 'next-business-day',
    },
    expect: {
      answerDate: '2026-08-17',
      finalCandidateDate: '2026-08-15',
      finalAdjustedDate: '2026-08-17',
      finalAdjustmentApplied: true,
      finalBlockedDates: ['2026-08-15', '2026-08-16'],
    },
  },
  {
    id: 'final-previous-business-day',
    layer: 'rules',
    description: 'Calendar-day candidate on Saturday moves backward to Friday',
    input: {
      triggerDate: '2026-08-14',
      duration: 1,
      direction: 'after',
      unit: 'calendar-days',
      startDayConvention: 'exclude-trigger',
      holidayCalendar: 'none',
      endDayAdjustment: 'previous-business-day',
    },
    expect: {
      answerDate: '2026-08-14',
      finalCandidateDate: '2026-08-15',
      finalAdjustedDate: '2026-08-14',
      finalAdjustmentApplied: true,
    },
  },
  {
    id: 'business-before-weekend',
    layer: 'rules',
    description: 'Backward business-day calculation skips a weekend',
    input: {
      triggerDate: '2026-08-17',
      duration: 1,
      direction: 'before',
      unit: 'business-days',
      startDayConvention: 'exclude-trigger',
      holidayCalendar: 'none',
      endDayAdjustment: 'none',
    },
    expect: {
      answerDate: '2026-08-14',
      skippedDates: ['2026-08-16', '2026-08-15'],
      skippedReasons: ['weekend'],
    },
  },
  {
    id: 'leap-year',
    layer: 'rules',
    description: 'Leap day is handled deterministically',
    input: {
      triggerDate: '2024-02-28',
      duration: 1,
      direction: 'after',
      unit: 'calendar-days',
      startDayConvention: 'exclude-trigger',
      holidayCalendar: 'none',
      endDayAdjustment: 'none',
    },
    expect: {
      answerDate: '2024-02-29',
    },
  },
  {
    id: 'year-boundary',
    layer: 'rules',
    description: 'Year boundary is handled deterministically',
    input: {
      triggerDate: '2026-12-31',
      duration: 1,
      direction: 'after',
      unit: 'calendar-days',
      startDayConvention: 'exclude-trigger',
      holidayCalendar: 'none',
      endDayAdjustment: 'none',
    },
    expect: {
      answerDate: '2027-01-01',
    },
  },
  {
    id: 'zero-duration',
    layer: 'rules',
    description: 'Zero duration returns the trigger date when no final adjustment applies',
    input: {
      triggerDate: '2026-08-10',
      duration: 0,
      direction: 'after',
      unit: 'calendar-days',
      startDayConvention: 'exclude-trigger',
      holidayCalendar: 'none',
      endDayAdjustment: 'none',
    },
    expect: {
      answerDate: '2026-08-10',
    },
  },
  {
    id: 'negative-duration-rejected',
    layer: 'rules',
    description: 'Negative durations are rejected',
    input: {
      triggerDate: '2026-08-10',
      duration: -1,
      direction: 'after',
      unit: 'calendar-days',
      startDayConvention: 'exclude-trigger',
      holidayCalendar: 'none',
      endDayAdjustment: 'none',
    },
    expectNull: true,
  },
  {
    id: 'version-provenance-retained',
    layer: 'rules',
    description: 'Structured answer retains rule, calendar, and schedule provenance',
    input: {
      triggerDate: '2026-08-10',
      duration: 3,
      direction: 'after',
      unit: 'business-days',
      startDayConvention: 'exclude-trigger',
      holidayCalendar: 'us',
      endDayAdjustment: 'none',
    },
    expect: {
      answerDate: '2026-08-13',
      ruleVersion: 'deadline-rule-v1',
      workingScheduleId: 'standard_mon_fri',
      holidayCalendar: 'us',
      holidayCalendarVersionPresent: true,
    },
  },

  // ---------------------------------------------------------------------------
  // Phrase interpretation -> structured request -> deterministic result
  // ---------------------------------------------------------------------------
  {
    id: 'phrase-explicit-after',
    layer: 'phrase',
    description: 'Explicit after wording resolves and calculates',
    phrase: '5 business days after 2026-08-10',
    expect: {
      classification: 'resolved',
      trigger: '2026-08-10',
      direction: 'after',
      duration: 5,
      unit: 'business days',
      result: '2026-08-17',
      ambiguityIncludes: [
        'holiday-calendar-defaulted',
        'start-day-rule-defaulted',
        'end-day-adjustment-defaulted',
      ],
    },
  },
  {
    id: 'phrase-explicit-before',
    layer: 'phrase',
    description: 'Explicit before wording resolves and calculates backward',
    phrase: '5 calendar days before 2026-08-10',
    expect: {
      classification: 'resolved',
      trigger: '2026-08-10',
      direction: 'before',
      duration: 5,
      unit: 'calendar days',
      result: '2026-08-05',
    },
  },
  {
    id: 'phrase-from-is-ambiguous',
    layer: 'phrase',
    description: '"From" preserves start-day ambiguity instead of pretending certainty',
    phrase: '5 business days from 2026-08-10',
    expect: {
      classification: 'ambiguous',
      trigger: '2026-08-10',
      result: '2026-08-17',
      ambiguityIncludes: ['start-day-rule'],
    },
  },
  {
    id: 'phrase-within-of-is-ambiguous',
    layer: 'phrase',
    description: '"Within ... of" preserves start-day ambiguity',
    phrase: 'within 5 business days of 2026-08-10',
    expect: {
      classification: 'ambiguous',
      trigger: '2026-08-10',
      result: '2026-08-17',
      ambiguityIncludes: ['start-day-rule'],
    },
  },
  {
    id: 'phrase-missing-trigger',
    layer: 'phrase',
    description: 'Missing trigger date is underspecified rather than guessed',
    phrase: '5 business days',
    expect: {
      classification: 'underspecified',
      trigger: null,
      result: null,
      missingIncludes: ['trigger-date'],
    },
  },
  {
    id: 'phrase-received-trigger',
    layer: 'phrase',
    description: 'Receipt wording becomes a canonical received trigger',
    phrase: '5 business days after receipt on 2026-08-10',
    expect: {
      classification: 'resolved',
      trigger: '2026-08-10',
      triggerEvent: 'received',
      triggerEventText: 'receipt',
      result: '2026-08-17',
    },
  },
  {
    id: 'phrase-today-reference',
    layer: 'phrase',
    description: 'Today is resolved only from the supplied deterministic today value',
    phrase: '5 business days after today',
    options: {
      today: '2026-08-10',
    },
    expect: {
      classification: 'resolved',
      trigger: '2026-08-10',
      result: '2026-08-17',
      ambiguityIncludes: ['today-reference'],
    },
  },
  {
    id: 'phrase-today-without-today-context',
    layer: 'phrase',
    description: 'Today without a supplied date context stays underspecified',
    phrase: '5 business days after today',
    expect: {
      classification: 'underspecified',
      trigger: null,
      result: null,
      missingIncludes: ['trigger-date'],
    },
  },
  {
    id: 'phrase-explicit-options-no-default-flags',
    layer: 'phrase',
    description: 'Explicit rule options suppress defaulted-assumption flags',
    phrase: '5 business days after 2026-08-10',
    options: {
      holidayCalendar: 'none',
      startDayConvention: 'include-if-qualifying',
      endDayAdjustment: 'none',
    },
    expect: {
      classification: 'resolved',
      trigger: '2026-08-10',
      result: '2026-08-14',
      exactAmbiguities: [],
    },
  },
  {
    id: 'phrase-holiday-aware',
    layer: 'phrase',
    description: 'Phrase interpretation delegates holiday-aware math to the deterministic engine',
    phrase: '1 business day after 2026-07-02',
    options: {
      holidayCalendar: 'us',
      startDayConvention: 'exclude-trigger',
      endDayAdjustment: 'none',
    },
    expect: {
      classification: 'resolved',
      trigger: '2026-07-02',
      result: '2026-07-06',
      exactAmbiguities: [],
    },
  },
  {
    id: 'phrase-unsupported-trigger-not-invented',
    layer: 'phrase',
    description: 'Unknown trigger wording is rejected instead of being invented',
    phrase: '5 business days after invoice on 2026-08-10',
    expectNull: true,
  },
]
