export enum RecoveryOutcome {
  ACCEPTED = "RETRY_ACCEPTED",
  NOT_FOUND = "OUTBOX_NOT_FOUND",
  INVALID_STATE = "NOT_DEAD_LETTER",
  AUTH_FAILURE = "UNAUTHORIZED_OPERATOR",
  INTERNAL_ERROR = "INTERNAL_ERROR"
}